### ISSUE TITLE
Опишите пожалуйста как пользоваться и для чего.

### ISSUE THREAD

**Issue by kompolom** [escaton/bem-chrome-devtools#3]
Установил. Открыл вкладку BEM. от мне показывает No blocks. И что дальше? для чего gulp?

**Comment by escaton** [comment]
А покажи пожалуйста, на какой страничке ты смотришь?

**Comment by escaton** [comment]
Про `gulp` не понял, он для сборки же.

**Comment by kompolom** [comment]
Ну я установил плагин в хром, открыл страницу с рабочим проектом, сверстанным по бэму, открыл dev-tools -> elements -> BEM и... ничего нет

**Comment by escaton** [comment]
Я имел в виду, можешь ли ты показать страничку, на который не видно блоков? В текущей версии отображение зависит от наличия фреймворка `i-bem` на страничке.
