### ISSUE TITLE
Расширение в магазине дополнений к Opera

### ISSUE THREAD

**Issue by tenorok** [escaton/bem-chrome-devtools#5]
Спасибо за классное дополнение!
Можно ли его зарегистрировать в магазине Opera?
https://addons.opera.com/ru/search/?query=BEM-devtools

**Comment by escaton** [comment]
Я отправил на валидацию две недели назад, увы, кажется opera store скорее мертв, чем жив(

**Comment by tenorok** [comment]
@escaton спасибо, жалко :'(
